#!/usr/bin/env python3
"""
gen_devicetree.py <board.dts> <devicetree_generated.h>

这是一个故意很小的 Devicetree 子集解析器，只服务 myrtos-buildskel 当前阶段：
- root 的 model / compatible
- chosen 里的 myrtos,console / myrtos,timer
- memory@... / flash@...
- 带 label 的 uart/timer 节点属性：reg / irq / current-speed / clock-frequency

它不是完整 DTS/dtc 替代品。目标是先把 Zephyr 的“硬件事实来自 DTS，C 代码使用生成头”
这条构建链路跑通。
"""
import re
import sys
from pathlib import Path


def strip_comments(text):
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.S)
    text = re.sub(r"//.*", "", text)
    return text


def parse_int(value):
    return int(value, 0)


def parse_cells(body, prop):
    match = re.search(rf"\b{re.escape(prop)}\s*=\s*<([^>]+)>\s*;", body)
    if not match:
        return []
    return [parse_int(part) for part in match.group(1).split()]


def parse_string(body, prop):
    match = re.search(rf"\b{re.escape(prop)}\s*=\s*\"([^\"]*)\"\s*;", body)
    return match.group(1) if match else None


def parse_ref(body, prop):
    match = re.search(rf"\b{re.escape(prop)}\s*=\s*&([A-Za-z_][A-Za-z0-9_]*)\s*;", body)
    return match.group(1) if match else None


def find_block(text, start_brace):
    depth = 0
    for index in range(start_brace, len(text)):
        char = text[index]
        if char == "{":
            depth += 1
        elif char == "}":
            depth -= 1
            if depth == 0:
                return text[start_brace + 1:index], index
    raise ValueError("unterminated DTS block")


def collect_labeled_nodes(text):
    nodes = {}
    pattern = re.compile(r"\b([A-Za-z_][A-Za-z0-9_]*)\s*:\s*[A-Za-z0-9_,\-]+@[A-Fa-f0-9x]+\s*\{")
    for match in pattern.finditer(text):
        body, _ = find_block(text, match.end() - 1)
        nodes[match.group(1)] = body
    return nodes


def find_node_by_prefix(text, prefix):
    match = re.search(rf"\b{re.escape(prefix)}@[A-Fa-f0-9x]+\s*\{{", text)
    if not match:
        raise ValueError(f"missing node: {prefix}@...")
    body, _ = find_block(text, match.end() - 1)
    return body


def emit_define(lines, name, value):
    if isinstance(value, str):
        lines.append(f'#define {name} "{value}"')
    else:
        lines.append(f"#define {name} 0x{value:X}")


def main():
    if len(sys.argv) != 3:
        print(f"用法: {sys.argv[0]} <board.dts> <devicetree_generated.h>", file=sys.stderr)
        return 1

    dts_path = Path(sys.argv[1])
    header_path = Path(sys.argv[2])
    text = strip_comments(dts_path.read_text(encoding="utf-8"))

    root_body, _ = find_block(text, text.index("{"))
    chosen_body = find_node_by_prefix(text.replace("chosen {", "chosen@0 {"), "chosen")
    nodes = collect_labeled_nodes(text)

    memory_reg = parse_cells(find_node_by_prefix(text, "memory"), "reg")
    flash_reg = parse_cells(find_node_by_prefix(text, "flash"), "reg")
    if len(memory_reg) != 2 or len(flash_reg) != 2:
        raise ValueError("memory/flash reg must contain <base size>")

    console_label = parse_ref(chosen_body, "myrtos,console")
    timer_label = parse_ref(chosen_body, "myrtos,timer")
    if not console_label or not timer_label:
        raise ValueError("chosen must define myrtos,console and myrtos,timer")
    if console_label not in nodes or timer_label not in nodes:
        raise ValueError("chosen references an unknown labeled node")

    console = nodes[console_label]
    timer = nodes[timer_label]
    console_reg = parse_cells(console, "reg")
    timer_reg = parse_cells(timer, "reg")
    console_irq = parse_cells(console, "irq")
    timer_irq = parse_cells(timer, "irq")
    console_baud = parse_cells(console, "current-speed")
    timer_clock = parse_cells(timer, "clock-frequency")

    if len(console_reg) != 2 or len(timer_reg) != 2:
        raise ValueError("console/timer reg must contain <base size>")

    lines = [
        "/* Generated by scripts/dts/gen_devicetree.py. Do not edit. */",
        "#ifndef DEVICETREE_GENERATED_H",
        "#define DEVICETREE_GENERATED_H",
        "",
    ]
    emit_define(lines, "DT_MODEL", parse_string(root_body, "model") or "unknown")
    emit_define(lines, "DT_COMPATIBLE", parse_string(root_body, "compatible") or "unknown")
    emit_define(lines, "DT_SRAM_BASE", memory_reg[0])
    emit_define(lines, "DT_SRAM_SIZE", memory_reg[1])
    emit_define(lines, "DT_FLASH_BASE", flash_reg[0])
    emit_define(lines, "DT_FLASH_SIZE", flash_reg[1])
    emit_define(lines, "DT_CONSOLE_LABEL", console_label)
    emit_define(lines, "DT_CONSOLE_BASE", console_reg[0])
    emit_define(lines, "DT_CONSOLE_SIZE", console_reg[1])
    emit_define(lines, "DT_CONSOLE_IRQ", console_irq[0] if console_irq else 0)
    emit_define(lines, "DT_CONSOLE_BAUD", console_baud[0] if console_baud else 0)
    emit_define(lines, "DT_TIMER_LABEL", timer_label)
    emit_define(lines, "DT_TIMER_BASE", timer_reg[0])
    emit_define(lines, "DT_TIMER_SIZE", timer_reg[1])
    emit_define(lines, "DT_TIMER_IRQ", timer_irq[0] if timer_irq else 0)
    emit_define(lines, "DT_TIMER_CLOCK_FREQUENCY", timer_clock[0] if timer_clock else 0)
    lines.extend(["", "#endif /* DEVICETREE_GENERATED_H */", ""])

    header_path.parent.mkdir(parents=True, exist_ok=True)
    header_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"[dts] {dts_path}")
    print(f"[dts] {header_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())