# SPDX-License-Identifier: Apache-2.0

include_guard(GLOBAL)

function(nerd_write_build_metadata output)
    if(BOARD_CANONICAL)
        set(_nerd_board ${BOARD_CANONICAL})
    else()
        set(_nerd_board ${BOARD})
    endif()

    set(_nerd_devicetree_header "")
    if(DEVICETREE_H AND EXISTS ${DEVICETREE_H})
        set(_nerd_devicetree_header ${DEVICETREE_H})
    endif()

    set(_nerd_hw_metadata_header "")
    if(NERD_HW_METADATA_H AND EXISTS ${NERD_HW_METADATA_H})
        set(_nerd_hw_metadata_header ${NERD_HW_METADATA_H})
    endif()

    set(_nerd_linker_memory_regions "")
    if(NERD_LINKER_MEMORY_REGIONS_LD AND EXISTS ${NERD_LINKER_MEMORY_REGIONS_LD})
        set(_nerd_linker_memory_regions ${NERD_LINKER_MEMORY_REGIONS_LD})
    endif()

    file(WRITE ${output}
"BOARD=${_nerd_board}\n"
"BOARD_INPUT=${BOARD}\n"
"BUILD_CONFIG=${BUILD_CONFIG}\n"
"CONFIG_BOARD_TARGET_MODEL=${CONFIG_BOARD_TARGET_MODEL}\n"
"CONFIG_BSP_RASPI_PICO2=${CONFIG_BSP_RASPI_PICO2}\n"
"CONFIG_ARCH_ARM_M33=${CONFIG_ARCH_ARM_M33}\n"
"CONFIG_ARCH_RISCV_RV32=${CONFIG_ARCH_RISCV_RV32}\n"
"ARCH_LAYER=${NERD_ARCH_LAYER}\n"
"ARCH_CPU=${NERD_ARCH_CPU}\n"
"ARCH_INSTRUCTION_SET=${NERD_ARCH_INSTRUCTION_SET}\n"
"ARCH_EXPECTED_COMPILE_OPTIONS=${NERD_ARCH_EXPECTED_COMPILE_OPTIONS}\n"
"ARCH_DIR=${NERD_ARCH_DIR}\n"
"ARCH_SOURCES=${NERD_ARCH_SOURCES}\n"
"ARCH_INCLUDE_DIRS=${NERD_ARCH_INCLUDE_DIRS}\n"
"SOC_DIR=${NERD_SOC_DIR}\n"
"SOC_SOURCES=${NERD_SOC_SOURCES}\n"
"SOC_INCLUDE_DIRS=${NERD_SOC_INCLUDE_DIRS}\n"
"BOARD_DIR=${NERD_BOARD_DIR}\n"
"BOARD_SOURCES=${NERD_BOARD_SOURCES}\n"
"BOARD_INCLUDE_DIRS=${NERD_BOARD_INCLUDE_DIRS}\n"
"SAMPLE_DIR=${NERD_SAMPLE_DIR}\n"
"SAMPLE_SOURCES=${NERD_SAMPLE_SOURCES}\n"
"SAMPLE_INCLUDE_DIRS=${NERD_SAMPLE_INCLUDE_DIRS}\n"
"LEGACY_BACKEND=${NERD_BOARD_LEGACY_DIR}\n"
"BSP_SOURCES=${NERD_BSP_SOURCES}\n"
"STARTUP_BACKEND=${NERD_STARTUP_BACKEND}\n"
"STARTUP_OWNER=${NERD_STARTUP_OWNER}\n"
"ENTRY_SOURCE=${NERD_ENTRY_SOURCE}\n"
"LINKER_SCRIPT=${NERD_LINKER_SCRIPT}\n"
"LINKER_INCLUDE_DIRS=${NERD_LINKER_INCLUDE_DIRS}\n"
"LINKER_MEMORY_REGIONS=${_nerd_linker_memory_regions}\n"
"TOOLCHAIN_BACKEND=${NERD_TOOLCHAIN_BACKEND}\n"
"PICO_BOARD=${PICO_BOARD}\n"
"PICO_PLATFORM=${PICO_PLATFORM}\n"
"PICO_SDK_SYSTEM_INCLUDE_DIRS=${NERD_PICO_SDK_SYSTEM_INCLUDE_DIRS}\n"
"PICO_PRINTF_IMPLEMENTATION=${NERD_PICO_PRINTF_IMPLEMENTATION}\n"
"PICO_EXTRA_OUTPUTS=${NERD_PICO_EXTRA_OUTPUTS}\n"
"PICO_LIBRARIES=${NERD_PICO_LIBRARIES}\n"
"DEVICETREE_SOURCE=${DEVICETREE_SOURCE}\n"
"DEVICETREE_HEADER=${_nerd_devicetree_header}\n"
"HW_METADATA_HEADER=${_nerd_hw_metadata_header}\n"
    )
endfunction()